theme = "gruvbox"

[editor]
mouse = true
auto-save = false
cursorline = true
cursorcolumn = false
bufferline = "always"
true-color = true
line-number = "relative"
scrolloff = 999
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
# left = ["mode", "spinner", "diagnostics"]
# center = ["file-name", "separator", "version-control", "separator"]
# right = ["position", "position-percentage", "total-line-numbers"]
left = ["separator", "version-control"]
center = ["file-name"]
right = []
separator = " "
# mode.normal = " 󰄛  "
# mode.insert = "   "
# mode.select = "   "

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = false

[editor.indent-guides]
render = true
character = "╎"

[editor.file-picker]
hidden = false
ignore = true

[keys.normal]
p = "paste_clipboard_before"
Y = "yank_main_selection_to_clipboard"
C-c = "normal_mode"
"A-h" = "goto_previous_buffer"
"A-l" = "goto_next_buffer"
"A-x" = ":buffer-close"
"0" = "goto_line_start"
"$" = "goto_line_end"
"G" = "goto_file_end"

[keys.normal.g]
"g" = "goto_file_start"

[keys.select]
"G" = "goto_file_end"

[keys.insert]
C-c = "normal_mode"
